version: '3.9'
services:
    nostr-nginx-fractal:
        container_name: nostr-nginx-fractal
        image: pastagringo/nostr-nginx-fractal:latest
        environment:
            LINK_DOMAIN_DEFAULT: $LINK_DOMAIN_DEFAULT
            USERNAME: pastagringo
            HEXKEY: b12b632c887f0c871d140d37bcb6e7c1e1a80264d0b7de8255aa1951d9e1ff79
    nostr-relay-fractal:
      container_name: nostr-relay-fractal
      image: pastagringo/nostr-relay-fractal:latest
      environment:
        - RELAY_URL=wss://$LINK_DOMAIN_DEFAULT
        - NAME=$LINK_DOMAIN_DEFAULT
        - DESCRIPTION=Nostr relay by PastaGringo powered by Fractalnetworks.co
        - PUBKEY=b12b632c887f0c871d140d37bcb6e7c1e1a80264d0b7de8255aa1951d9e1ff79
        - CONTACT=pastagringo@skiff.com
        - PORT=8080
        - FAVICON_URL=https://www.linkpicture.com/q/favicon_78.ico
        - NIP05=enabled
    link:
      container_name: nostr-relay-fractal-link
      image: fractalnetworks/link:latest
      environment:
        LINK: $LINK_DOMAIN_DEFAULT
        TOKEN: $LINK_TOKEN_DEFAULT
        EXPOSE: nostr-nginx-fractal:80
        FRACTAL_API: https://gateway.fractalnetworks.co
      cap_add:
        - NET_ADMIN
      volumes:
        - fractal-link-volume:/root/.local/share/caddy
volumes:
  fractal-link-volume:
    external: true
    name: $LINK_VOLUME_NAME
