version: '3.9'
services:
    nostr-relay-nginx-fractal:
        container_name: nostr-relay-nginx-fractal
        image: pastagringo/nostr-relay-nginx-proxy:latest
        environment:
            LINK_DOMAIN_DEFAULT: $LINK_DOMAIN_DEFAULT        
    nostr-relay-fractal:
      container_name: nostr-relay-fractal
      image: pastagringo/nostr-relay-fractal:latest
      environment:
        - RELAY_URL=wss://$LINK_DOMAIN_DEFAULT
        - NAME=$LINK_DOMAIN_DEFAULT
        - DESCRIPTION=Nostr relay by PastaGringo powered by Fractalnetworks.co
        - PUBKEY=npub1ky4kxtyg0uxgw8g5p5mmedh8c8s6sqny6zmaaqj44gv4rk0plaus3m4fd2
        - CONTACT=pastagringo@skiff.com
        - PORT=8080
        #- NIP05=enabled
#      volumes:
#        - fractal-app-volume:/usr/src/app/db
    link:
      container_name: nostr-rs-relay-fractal-link
      image: fractalnetworks/link:latest
      environment:
        LINK: $LINK_DOMAIN_DEFAULT
        TOKEN: $LINK_TOKEN_DEFAULT
        EXPOSE: nostr-relay-nginx-fractal:80
        FRACTAL_API: https://gateway.fractalnetworks.co
      cap_add:
        - NET_ADMIN
      volumes:
        - fractal-link-volume:/root/.local/share/caddy
volumes:
#  fractal-app-volume:
#    external: true
#    name: $APP_VOLUME_NAME
  fractal-link-volume:
    external: true
    name: $LINK_VOLUME_NAME
