services:
  link:
    environment:
      EXPOSE: filerun:80
    volumes:
      - fractal-link-volume:/root/.local/share/caddy
  filerun_db:
    container_name: filerun_db
    image: mariadb:10.1
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      MYSQL_USER: your_filerun_username
      MYSQL_PASSWORD: your_filerun_password
      MYSQL_DATABASE: your_filerun_database
    volumes:
      - fractal-app-volume-filerun-db:/var/lib/mysql
  filerun:
    image: filerun/filerun
    container_name: filerun
    environment:
      FR_DB_HOST: filerun_db
      FR_DB_PORT: 3306
      FR_DB_NAME: your_filerun_database
      FR_DB_USER: your_filerun_username
      FR_DB_PASS: your_filerun_password
      APACHE_RUN_USER: www-data
      APACHE_RUN_USER_ID: 33
      APACHE_RUN_GROUP: www-data
      APACHE_RUN_GROUP_ID: 33
    depends_on:
      - filerun_db
    links:
      - filerun_db:filerun_db
    #ports:
    #  - "80:80"
    volumes:
      - fractal-app-volume-filerun-html:/var/www/html
      - fractal-app-volume-filerun-files:/user-files
    healthcheck:
      test: curl localhost:80
      interval: 10s
      timeout: 10s
      retries: 5
volumes:
  fractal-link-volume:
    external: true
    name: $LINK_VOLUME_NAME
  fractal-app-volume-filerun-db:
    external: true
    name: $APP_VOLUME_NAME
  fractal-app-volume-filerun-html:
    external: true
    name: $APP_VOLUME_NAME
  fractal-app-volume-filerun-files:
    external: true
    name: $APP_VOLUME_NAME
